server.port=8086
spring.application.name=task-service
eureka.client.enabled=${EUREKA_CLIENT_ENABLED:true}
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
app.jwt.secret=YhCZHWj0CkZU+HIMHLC539V0iITbcGmV6wyeeWKkba5j3k+zKSlLRxtwHjeGb3xBa7e+i3WQDIyKjqN6kGqVcw==
app.jwt.expiration-ms=86400000
app.internal.secret=shared-internal-secret

spring.datasource.url=${TASK_DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
