server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  client:
    enabled: ${EUREKA_CLIENT_ENABLED:true}
    service-url:
      defaultZone: http://localhost:8761/eureka/

services:
  auth:
    uri: lb://auth-service
  project:
    uri: lb://project-service
  task:
    uri: lb://task-service
  comment:
    uri: lb://comment-service
  jira:
    uri: lb://jira-service
