services:
  # The monolith we are currently strangling
  monolith:
    build: .
    ports:
      - "8081:8080" # Moved from 8080 to 8081 to free 8080 for the gateway
    environment:
      - JIRA_URL=${JIRA_URL}
      - JIRA_EMAIL=${JIRA_EMAIL}
      - JIRA_API_TOKEN=${JIRA_API_TOKEN}
      - JIRA_LEAD_ACCOUNT_ID=${JIRA_LEAD_ACCOUNT_ID}

  # The future entry point
  gateway:
    image: springcloud/spring-cloud-gateway # Placeholder
    ports:
      - "8080:8080"
    depends_on:
      - monolith
      - auth-service

  # The future Auth service
  auth-service:
    build: ./auth-service # Placeholder for Phase 3
    depends_on:
      - monolith

  frontend:
    build: ./client
    ports:
      - "3000:80"
    depends_on:
      - gateway
