server.port=8084
spring.application.name=jira-service
app.jwt.secret=YhCZHWj0CkZU+HIMHLC539V0iITbcGmV6wyeeWKkba5j3k+zKSlLRxtwHjeGb3xBa7e+i3WQDIyKjqN6kGqVcw==
app.jwt.expiration-ms=86400000


# Jira Configuration - Mapped to Env Vars
jira.url=${JIRA_URL:http://localhost:8081}
jira.email=${JIRA_EMAIL:admin@example.com}
jira.api.token=${JIRA_API_TOKEN:dummy_token}
jira.lead.account.id=${JIRA_LEAD_ACCOUNT_ID:dummy_id}
