server.port=8084
spring.application.name=jira-service
eureka.client.enabled=${EUREKA_CLIENT_ENABLED:true}
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
spring.datasource.url=${JIRA_DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
app.jwt.secret=YhCZHWj0CkZU+HIMHLC539V0iITbcGmV6wyeeWKkba5j3k+zKSlLRxtwHjeGb3xBa7e+i3WQDIyKjqN6kGqVcw==
app.jwt.expiration-ms=86400000
app.internal.secret=shared-internal-secret
project.service.url=http://localhost:8085
task.service.url=http://localhost:8086
comment.service.url=http://localhost:8083

# Jira Configuration - Mapped to Env Vars
jira.url=${JIRA_URL:http://localhost:8081}
jira.email=${JIRA_EMAIL:admin@example.com}
jira.api.token=${JIRA_API_TOKEN:dummy_token}
jira.lead.account.id=${JIRA_LEAD_ACCOUNT_ID:dummy_id}
