CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    username VARCHAR(255) NOT NULL,
    encrypted_password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    role VARCHAR(255) NOT NULL,
    refresh_token VARCHAR(1000)
);

INSERT INTO users (email, username, encrypted_password, role, created_at)
VALUES ('avruis@gmail.com', 'user', '$2a$10$diNBCSd9LfE6bMBdi4Nag.Hd2cVQxyI1xIWTZ1x4xqPhzCCf3WDaO', 'USER', CURRENT_TIMESTAMP);

